name: Build DeepSeek V1 DLL

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-dll:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Create DLL Source Code
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Path src -Force | Out-Null
        $code = @(
          '#include <windows.h>',
          '',
          'BOOL APIENTRY DllMain(HMODULE hModule, DWORD reason, LPVOID reserved)',
          '{',
          '    return TRUE;',
          '}',
          '',
          'extern "C" __declspec(dllexport) void DeepSeek_Function() {}'
        )
        $code | Set-Content -Path src/DeepSeekV1.cpp -Encoding ascii

    - name: Compile DLL
      shell: cmd
      run: |
        cl /LD src\DeepSeekV1.cpp /Fe:DeepSeekV1.dll

        if not exist DeepSeekV1.dll (
          echo ::error::DLL build failed
          exit 1
        )

    - name: Upload DLL Artifact (im gay joke)
      uses: actions/upload-artifact@v4
      with:
        name: DeepSeekV1-2
        path: DeepSeekV1-2.dll
        if-no-files-found: error
        retention-days: 7
