name: Build DeepSeek Menu V1 Alpha

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Build Solution
      run: msbuild YourSolution.sln /p:Configuration=Release /p:Platform=x64 /p:OutDir=artifacts\
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: DeepSeek-V1
        path: artifacts\*.dll