name: Build DeepSeek V1 Gorilla Tag Menu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Build Solution
      run: |
        # Create artifacts directory if it doesn't exist
        if not exist artifacts mkdir artifacts
        msbuild YourSolution.sln `
          /p:Configuration=Release `
          /p:Platform=x64 `
          /p:OutDir=artifacts\
      
    - name: Upload DLL Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DeepSeek-V1
        path: artifacts\*.dll
        if-no-files-found: error
