name: Build DeepSeek V1 Menu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Build DLL
      shell: cmd
      run: |
        msbuild "DeepSeekV1.vcxproj" ^
          /p:Configuration=Release ^
          /p:Platform=x64 ^
          /p:OutDir=.\artifacts\ ^
          /p:TargetName=DeepSeekV1
        
        dir /b artifacts\DeepSeekV1.dll || exit 1
        
    - name: Upload DLL
      uses: actions/upload-artifact@v4
      with:
        name: DeepSeekV1-Menu
        path: artifacts\DeepSeekV1.dll
        if-no-files-found: error
